@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Admin" as Adm

activate Adm
Adm -> System: Create new backoffice user 
activate System
Adm <-- System: Inform Success
deactivate System

@enduml