@startuml

skinparam linetype ortho

node Server1{
   component "<<Visualization>>" as V {
    }
}

node Server2{
  component "<<MasterDataLogistic>>" as MDL{
  }

  component "<<MasterDataBuilding>>" as MDB{
  }
}

node Server3{
  component "<<Planning>>" as P {
  }
}

node Server4{
  database MongoDB
}

node Server5{
  database Auth
}

node Server6{
  database Database
}




Server2 -u- Server4
Server5 -u- Server6
@enduml
